DROP TABLE EMPLOYEEE;
DROP TABLE REIMBURSEMENT;



CREATE TABLE EMPLOYEEE (
    EMPLOYEEID number NOT NULL,
    FIRSTNAME varchar2(100) NOT NULL,
    LASTNAME varchar2(100) NOT NULL,
    PASSWD varchar2(100) NOT NULL,
    USERNAME varchar2(100) NOT NULL,
    RID number NOT NULL,
    IS_MANAGER INTEGER DEFAULT 0 CHECK (IS_MANAGER = 0 OR IS_MANAGEr = 1),
    
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEEID)
);


CREATE TABLE REIMBURSEMENT(
    RID number NOT NULL,
    TOTAL number NOT NULL,
    
     CONSTRAINT PK_REIMBURSEMENT PRIMARY KEY (RID)
);







ALTER TABLE EMPLOYEEE ADD CONSTRAINT FK_RID
    FOREIGN KEY (RID) REFERENCES REIMBURSEMENT (RID)  ;
    
INSERT INTO REIMBURSEMENT
VALUES(1, 100); 
INSERT INTO REIMBURSEMENT
VALUES(2, 540); 
INSERT INTO REIMBURSEMENT
VALUES(3, 230); 
    
INSERT INTO EMPLOYEEE
VALUES(1, 'Sam', 'Yin', 'lala', 'samy', 1, 1);
INSERT INTO EMPLOYEEE
VALUES(2, 'Alex', 'Yin', 'lsala', 'alexy', 2, 0);
INSERT INTO EMPLOYEEE
VALUES(3, 'Ben', 'Yin', 'lsdfla', 'beben', 3, 0);


/*

CREATE SEQUENCE inc_employ START WITH 1;
CREATE SEQUENCE inc_emprid START WITH 1;
CREATE SEQUENCE inc_reimb START WITH 1;

CREATE OR REPLACE TRIGGER inc_employ
BEFORE INSERT ON EMPLOYEEE 
FOR EACH ROW
BEGIN
  SELECT inc_employ.NEXTVAL
  INTO   :new.employeeid
  FROM   dual;
END;
/


CREATE OR REPLACE TRIGGER inc_emprid
BEFORE INSERT ON EMPLOYEEE 
FOR EACH ROW
BEGIN
  SELECT inc_emprid.NEXTVAL
  INTO   :new.rid
  FROM   dual;
END;
/

CREATE OR REPLACE TRIGGER inc_reimb
BEFORE INSERT ON REIMBURSEMENT
FOR EACH ROW
BEGIN
  SELECT inc_reimb.NEXTVAL
  INTO   :new.rid
  FROM   dual;
END;
/
*/

commit;